---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: false
    - name: "02-installing-c2r"
      label: "Installing C2r"
      solveButton: false
    - name: "03-analyze"
      label: "Analyze"
      solveButton: false
    - name: "04-running-c2r"
      label: "Running C2r"
      solveButton: false
    - name: "05-completing-conversion"
      label: "Completing Conversion"
      solveButton: false

tabs:
  - name: "controlnode"
    url: /wetty_controlnode/ssh/root
  - name: "centos"
    url: /wetty_centos/ssh/root
