---
virtualmachines:
  - name: "host"
    image: "centos-convert2rhel"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
