---
virtualmachines:
  - name: "host"
    image: "savage-minimal-centos-7.9-hvm-std01.x86_64-gp2"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
