---
virtualmachines:
  - name: "host"
    image: "savage-minimal-centos-7.9-hvm-std01.x86_64-gp2"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    UserData: |
      {% filter indent(width=6) %}
      UserData:
        "Fn::Base64":
            "Fn::Join":
              - ""
              - - "#cloud-config\n"
                - "users:\n"
                - "  - default\n"
                - "  - name: ec2-user\n"
                - "    lock_passwd: true\n"
                - "    gecos: Cloud User\n"
                - "    groups: [adm, systemd-journal]\n"
                - "    sudo: ['ALL=(ALL) NOPASSWD:ALL']\n"
                - "    shell: /bin/bash\n"
                - "    ssh-authorized-keys:\n"
                - "    ssh_authorized_keys:\n"
                - "      - {{ hostvars.localhost.ssh_provision_pubkey_content | default('') }}\n"
      {% endfilter %}
